/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehicles.models;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rui Barcelos
 */
public final class EditModel extends javax.swing.JFrame {

    /**
     * Creates new form ChangeModel
     *
     * @param login
     * @param id
     * @param brand
     * @throws java.lang.Exception
     */
    public EditModel(String login, int id, String brand) throws Exception {
        APIModel api = new APIModel();
        initComponents();
        l_brand.setText(brand);
        InfoModel(login, id, api);
        Events(login, id, api);
    }

    /**
     * Eventos
     *
     * @param login
     * @param id
     * @param api
     * @throws Exception
     */
    private void Events(final String login, final int id, final APIModel api) throws Exception {
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    BT_EDIT(evt, login, id, api);
                } catch (Exception ex) {
                    Logger.getLogger(EditModel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     * Mostra a informação do modelo
     *
     * @param login
     * @param id
     * @param api
     * @throws Exception
     */
    private void InfoModel(String login, int id, APIModel api) throws Exception {
        String model[] = api.InfoModel(login, id);
        l_id.setText(model[0]);
        tf_name.setText(model[1]);
    }

    /**
     * Edita o nome do modelo depois de ser confirmado e verificado pelo sistema
     *
     * @param evt
     * @param login
     * @param id
     * @param api
     * @throws Exception
     */
    private void BT_EDIT(java.awt.event.ActionEvent evt, String login, int id, APIModel api) throws Exception {
        if (tf_name.getText().length() < 25 && tf_name.getText().length() > 1) {
            String modelName = api.InfoModel(login, id)[1];
            int x = JOptionPane.showConfirmDialog(this, "Quer modificar a marca " + modelName + " para " + tf_name.getText() + "?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (x == JOptionPane.YES_OPTION) {
                String[] value = api.PutModel(login, id, tf_name.getText());
                JOptionPane.showMessageDialog(this, value[1]);
                if ("ok".equals(value[0])) {
                    new Table_Model(login).setVisible(true);
                    dispose();
                }
            } else if (x == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(this, "A Marca " + modelName + " não foi modificada");
            }
        } else {
            JOptionPane.showMessageDialog(this, "O modelo tem de ter entre 2 a 25 caracteres");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        l_id = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        bt_edit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        l_brand = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GestRepair - Editar Modelo");

        jLabel2.setText("Modelo:");

        l_id.setText("id");

        bt_edit.setText("Editar");

        jLabel3.setText("Marca:");

        l_brand.setText("jLabel4");

        jLabel4.setText("Editar Modelo n.º:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_edit)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_id))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_brand)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(l_id))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(l_brand))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_edit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(228, 186));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_edit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel l_brand;
    private javax.swing.JLabel l_id;
    private javax.swing.JTextField tf_name;
    // End of variables declaration//GEN-END:variables
}
