/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehicles.brands;

import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.xml.bind.DatatypeConverter.parseInt;

/**
 *
 * @author Rui Barcelos
 */
public final class EditBrand extends javax.swing.JFrame {

    /**
     * Creates new form ChangeBrand
     *
     * @param login
     * @param id
     * @throws java.lang.Exception
     */
    public EditBrand(String login, int id) throws Exception {
        APIBrand api = new APIBrand();
        initComponents();
        InfoBrand(login, id, api);
        Events(login, api);
    }

    private void InfoBrand(String login, int id, APIBrand api) throws Exception {
        String brand[] = api.InfoBrand(login, id);
        l_id.setText(brand[0]);
        tf_name.setText(brand[1]);
    }

    private void ChangeBrand(String login, int id, String name, APIBrand api) throws Exception {
        int x = JOptionPane.showConfirmDialog(this, "Quer modificar a marca " + api.InfoBrand(login, id)[1] + " para " + tf_name.getText() + "?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            String value[] = api.PutBrand(login, id, name);
            JOptionPane.showMessageDialog(this, value[1]);
            if ("ok".equals(value[0])) {
                new Table_Brand(login).setVisible(true);
                dispose();
            }
        } else if (x == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "A Marca " + api.InfoBrand(login, id)[1] + " não foi modificada");
        }
    }

    private void Events(final String login, final APIBrand api) {
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_EDIT(evt, login, api);
            }
        });
    }

    private void BT_EDIT(java.awt.event.ActionEvent evt, String login, APIBrand api) {
        try {
            ChangeBrand(login, parseInt(l_id.getText()), tf_name.getText(), api);
        } catch (Exception ex) {
            Logger.getLogger(EditBrand.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l_id = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        bt_edit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GestRepair - Editar Marca");

        jLabel1.setText("ID:");

        jLabel2.setText("Marca:");

        l_id.setText("id");

        bt_edit.setText("Editar");

        jLabel3.setText("Editar marca automóvel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_edit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 126, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_id)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tf_name))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(l_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_edit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(275, 150));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel l_id;
    private javax.swing.JTextField tf_name;
    // End of variables declaration//GEN-END:variables
}
