/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehicles.vehicles;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rui Barcelos
 */
public class InfoVehicle extends javax.swing.JFrame {

    /**
     * Creates new form Info_Vehicle
     *
     * @param login
     * @param id
     */
    public InfoVehicle(String login, int id) {
        APIVehicles api = new APIVehicles();
        initComponents();
        Info(login, id, api);
        Events(login, id);
    }

    /**
     * Eventos
     *
     * @param login
     * @param id
     */
    private void Events(final String login, final int id) {
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_EDIT(evt, login, id);
            }
        });
    }

    /**
     * Mostra a informação da form
     *
     * @param login
     * @param id
     * @param api
     */
    private void Info(String login, int id, APIVehicles api) {
        try {
            String[] info = api.InfoVehicle(login, id);
            l_id.setText(info[0]);
            l_brand.setText(info[1]);
            l_model.setText(info[2]);
            l_registration.setText(info[3]);
            l_horsepower.setText((info[4] != null) ? info[4] : "");
            l_displacement.setText((info[5] != null) ? info[5] : "");
            l_kilometer.setText((info[6] != null) ? info[6] : "");
            l_fuel.setText(info[7]);
            l_fronrizetire.setText(info[8]);
            l_rearrizetire.setText(info[9]);
            l_date.setText(info[10]);
        } catch (Exception ex) {
            Logger.getLogger(InfoVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Abre a form de editar viatura
     *
     * @param evt
     * @param login
     * @param id
     */
    private void BT_EDIT(java.awt.event.ActionEvent evt, String login, int id) {
        try {
            new EditVehicle(login, id).setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(InfoVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        l_id = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l_registration = new javax.swing.JLabel();
        l_brand = new javax.swing.JLabel();
        l_model = new javax.swing.JLabel();
        l_fuel = new javax.swing.JLabel();
        l_date = new javax.swing.JLabel();
        l_horsepower = new javax.swing.JLabel();
        l_displacement = new javax.swing.JLabel();
        l_kilometer = new javax.swing.JLabel();
        l_fronrizetire = new javax.swing.JLabel();
        l_rearrizetire = new javax.swing.JLabel();
        bt_edit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GestRepair - Informação da Viatura");
        setResizable(false);

        jLabel10.setText("Combustível");

        jLabel7.setText("CV");

        jLabel8.setText("Cilindrada");

        jLabel11.setText("Data");

        jLabel6.setText("Pneu Trás");

        jLabel5.setText("Pneu Frente");

        jLabel1.setText("Marca");

        jLabel9.setText("Quilómetros");

        l_id.setText("ID");

        jLabel4.setText("Modelo");

        jLabel3.setText("Matrícula");

        l_registration.setText("Matrícula");

        l_brand.setText("Marca");

        l_model.setText("modelo");

        l_fuel.setText("combustivel");

        l_date.setText("Data");

        l_horsepower.setText("cavalos");

        l_displacement.setText("cilindrada");

        l_kilometer.setText("Quilómetros");

        l_fronrizetire.setText("medida frente");

        l_rearrizetire.setText("medida traz");

        bt_edit.setText("Editar");

        jLabel12.setText("Detalhes da viatura n.º:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(39, 39, 39)
                                .addComponent(l_id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 211, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(l_date)
                                            .addComponent(l_fuel)
                                            .addComponent(jLabel3)))
                                    .addComponent(l_registration)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(54, 54, 54)
                                        .addComponent(l_brand))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(49, 49, 49)
                                        .addComponent(l_model)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(l_horsepower)
                                            .addComponent(l_displacement)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(l_kilometer))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(l_rearrizetire)
                                            .addComponent(l_fronrizetire))))))
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(l_id))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(l_horsepower))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(l_displacement))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_kilometer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(l_fronrizetire))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(l_rearrizetire)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_registration)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(l_brand))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(l_model))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(l_fuel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(l_date))))
                .addGap(38, 38, 38)
                .addComponent(bt_edit)
                .addGap(25, 25, 25))
        );

        setSize(new java.awt.Dimension(507, 288));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel l_brand;
    private javax.swing.JLabel l_date;
    private javax.swing.JLabel l_displacement;
    private javax.swing.JLabel l_fronrizetire;
    private javax.swing.JLabel l_fuel;
    private javax.swing.JLabel l_horsepower;
    private javax.swing.JLabel l_id;
    private javax.swing.JLabel l_kilometer;
    private javax.swing.JLabel l_model;
    private javax.swing.JLabel l_rearrizetire;
    private javax.swing.JLabel l_registration;
    // End of variables declaration//GEN-END:variables
}
