/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehicles.fuel;

import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rui Barcelos
 */
public class InfoFuel extends javax.swing.JFrame {

    /**
     * Creates new form Info_Vehicle
     *
     * @param login
     * @param id
     */
    public InfoFuel(String login, int id) {
        APIFuel api = new APIFuel();
        initComponents();
        Info(login, id, api);
        Events(login, id, api);

    }
    private void Events(final String login, final int id,final APIFuel api) {
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_EDIT(evt, login, id);
            }
        });
    }
    private void Info(String login, int id, APIFuel api) {
        try {
            String[] info = api.InfoFuel(login, id);
            l_id.setText(info[0]);
            l_fuel.setText(info[1]);

        } catch (Exception ex) {
            Logger.getLogger(InfoFuel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void BT_EDIT(java.awt.event.ActionEvent evt, String login, int id) {                                        
        try {
            new EditFuel(login, id).setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(InfoFuel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        l_id = new javax.swing.JLabel();
        l_fuel = new javax.swing.JLabel();
        bt_edit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GestRepair - Informação do Combustível");
        setResizable(false);

        jLabel10.setText("Combustível");

        l_id.setText("ID");

        l_fuel.setText("combustivel");

        bt_edit.setText("Editar");

        jLabel1.setText("Detalhes do Combustivel N.º:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_fuel))
                    .addComponent(bt_edit)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(l_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(l_fuel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_edit)
                .addGap(6, 6, 6))
        );

        setSize(new java.awt.Dimension(210, 124));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel l_fuel;
    private javax.swing.JLabel l_id;
    // End of variables declaration//GEN-END:variables
}
