/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehicles;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Convite
 */
public class MainVehicles extends javax.swing.JFrame {
    public String log;
    /**
     * Creates new form mainVehicles
     */
    public MainVehicles(String login) {
        initComponents();
        log = login;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_showvehicles = new javax.swing.JButton();
        bt_model = new javax.swing.JButton();
        bt_addBrand = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        bt_showvehicles.setText("Ver Veiculos");
        bt_showvehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_showvehiclesActionPerformed(evt);
            }
        });

        bt_model.setText("Adicionar Modelo");
        bt_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modelActionPerformed(evt);
            }
        });

        bt_addBrand.setText("Adicionar Marca");
        bt_addBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addBrandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_model, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(bt_addBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_showvehicles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bt_showvehicles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(bt_addBrand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_model)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addBrandActionPerformed
        // TODO add your handling code here:
        new AddBrand(log).setVisible(true);
    }//GEN-LAST:event_bt_addBrandActionPerformed

    private void bt_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modelActionPerformed
        try {
            new AddModel(log).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainVehicles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_modelActionPerformed

    private void bt_showvehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_showvehiclesActionPerformed
        try {
            new Table_Vehicles(log).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainVehicles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_showvehiclesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addBrand;
    private javax.swing.JButton bt_model;
    private javax.swing.JButton bt_showvehicles;
    // End of variables declaration//GEN-END:variables
}
