/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package users.user;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author Rui Barcelos
 */
public class EditPassword extends javax.swing.JFrame {

    /**
     * Creates new form EditPassword
     *
     * @param login
     * @param id
     * @throws java.lang.Exception
     */
    public EditPassword(String login, int id) throws Exception {
        APIUsers api = new APIUsers();
        initComponents();
        JSONObject auth = (JSONObject) new JSONParser().parse(login);
        Events(login, id, (String) auth.get("password"), api);

    }

    /**
     * Define os eventos
     *
     * @param login
     * @param id
     * @param password
     * @param api
     */
    private void Events(final String login, final int id, final String password, final APIUsers api) {
        bt_chpass.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    BT_ChangePass(evt, login, id, password, api);
                } catch (Exception ex) {
                    Logger.getLogger(EditPassword.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    /**
     * Validação
     */
    private static final Pattern VALID_PASS_REGEX = Pattern.compile("^(?:(?=.*[a-z])(?:(?=.*[A-Z])(?=.*[\\d\\W])|(?=.*\\W)(?=.*\\d))|(?=.*\\W)(?=.*[A-Z])(?=.*\\d)).{8,}$", Pattern.CASE_INSENSITIVE);

    private static boolean validatePASS(String pass) {
        Matcher matcher = VALID_PASS_REGEX.matcher(pass);
        return matcher.find();
    }

    /**
     * Altera password caso seja confirmado pelo utilizador a ação
     *
     * @param evt
     * @param login
     * @param id
     * @param password
     * @param api
     * @throws Exception
     */
    private void BT_ChangePass(java.awt.event.ActionEvent evt, String login, int id, String password, APIUsers api) throws Exception {
        if (validatePASS(tf_npass.getText()) == true) {
            int x = JOptionPane.showConfirmDialog(this, "Tem a certeza que quer alterar a sua password?", "GestRepair", JOptionPane.YES_NO_OPTION);
            if (x == JOptionPane.YES_OPTION) {
                if (password.equals(tf_pass_act.getText())) {
                    if (!tf_npass.getText().equals(password) || !tf_npass.getText().equals(password)) {
                        if (tf_npass.getText().equals(tf_cpass.getText())) {
                            String[] value = api.PutPassword(login, id, password, tf_npass.getText());
                            JOptionPane.showMessageDialog(this, value[1] + (("ok".equals(value[0])) ? "\nO sistema irá desligar!" : ""));
                            if ("ok".equals(value[0])) {
                                System.exit(0);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "A nova password não coicide com a de confirmação");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "A nova password é igual à actual");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "A Password atual é não é igual à do sistema");
                }
            } else if (x == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(this, "A Password não foi alterada");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Verifique se a nova password com pelo menos 8 caracteres e uma letra maiuscula/caracter especial.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_pass_act = new javax.swing.JPasswordField();
        tf_npass = new javax.swing.JPasswordField();
        tf_cpass = new javax.swing.JPasswordField();
        l_pass_act = new javax.swing.JLabel();
        l_npass = new javax.swing.JLabel();
        l_cpass = new javax.swing.JLabel();
        bt_chpass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GestRepair - Alterar Password");

        l_pass_act.setText("Password Atual:");

        l_npass.setText("Nova Password:");

        l_cpass.setText("Confirmação Password:");

        bt_chpass.setText("Alterar Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_cpass)
                    .addComponent(l_npass)
                    .addComponent(l_pass_act))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_chpass, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(tf_pass_act)
                    .addComponent(tf_npass)
                    .addComponent(tf_cpass))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_pass_act)
                    .addComponent(tf_pass_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_npass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_npass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_cpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_cpass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_chpass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(365, 162));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_chpass;
    private javax.swing.JLabel l_cpass;
    private javax.swing.JLabel l_npass;
    private javax.swing.JLabel l_pass_act;
    private javax.swing.JPasswordField tf_cpass;
    private javax.swing.JPasswordField tf_npass;
    private javax.swing.JPasswordField tf_pass_act;
    // End of variables declaration//GEN-END:variables

}
