/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package budgets;

import static java.lang.Integer.parseInt;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Rui Barcelos
 */
public final class Table_Budgets extends javax.swing.JFrame {
    
    /**
     * Creates new form Table_Vehicles
     * @param login
     * @throws java.io.IOException
     * @throws java.net.MalformedURLException
     * @throws org.json.simple.parser.ParseException
     */
    public Table_Budgets(String login) throws Exception {
        APIBudgets api = new APIBudgets();
        initComponents();
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../img/imageedit_4_8303763918.png")));
        showTable(api.ListBudgets(login,0));
        l_idBudget.setText((String) tbl_budgets.getModel().getValueAt(0, 0));
        Events(login);
    }
        
    private void showTable(String[][] list) {
        DefaultTableModel mod = (DefaultTableModel) tbl_budgets.getModel();
        Object[] row = new Object[9];
        for (String[] list1 : list) {
            for (int i = 0; i < row.length; i++) {
                if(i == 5||i == 6){
                    row[i] = list1[i];
                }else{
                    row[i] = list1[i];
                }
            }
            mod.addRow(row);
        }
    }
    private void Events(final String login){
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_Edit(evt,login);
            }
        });
        bt_info.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_Info(evt,login);
            }
        });
        tbl_budgets.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_budgetsClicked(evt);
            }
        });
    }
       
    private void BT_Edit(java.awt.event.ActionEvent evt, String login) {                                        
        // TODO add your handling code here:
        try {
            TableModel mod = tbl_budgets.getModel();
            int i = tbl_budgets.getSelectedRow();
            new EditBudget(login, parseInt((String)mod.getValueAt(i, 0))).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Table_Budgets.class.getName()).log(Level.SEVERE, null, ex);
        }
    }   
    private void BT_Info(java.awt.event.ActionEvent evt, String login) {                                        
        // TODO add your handling code here:
        try {
            TableModel mod = tbl_budgets.getModel();
            int i = tbl_budgets.getSelectedRow();
            new InfoBudget(login, parseInt((String)mod.getValueAt(i, 0))).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Table_Budgets.class.getName()).log(Level.SEVERE, null, ex);
        }
    }   
    private void TBL_budgetsClicked(java.awt.event.MouseEvent evt) {                                         
        int i = tbl_budgets.getSelectedRow();
        TableModel mod = tbl_budgets.getModel();
        l_idBudget.setText((String) mod.getValueAt(i, 0));
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_budgets = new javax.swing.JTable();
        bt_edit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        l_idBudget = new javax.swing.JLabel();
        bt_info = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GestRepair - Lista de Orçamentos");
        setResizable(false);

        tbl_budgets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Matrícula", "Desc.Cliente", "Preço", "Entrada", "Tempo de Reparação", "Fim do Processo", "Resolução", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_budgets.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tbl_budgets);
        tbl_budgets.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        bt_edit.setText("Editar ");

        jLabel7.setText("Orçamento  N.º");

        l_idBudget.setText("orçamento");

        bt_info.setText("Info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_idBudget)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_edit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_edit)
                        .addComponent(bt_info))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_idBudget)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1216, 584));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_edit;
    private javax.swing.JButton bt_info;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_idBudget;
    private javax.swing.JTable tbl_budgets;
    // End of variables declaration//GEN-END:variables
}
