/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package services;

import java.awt.Image;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Rui Barcelos
 */
public final class InfoService extends javax.swing.JFrame {

    /**
     * Creates new form EditService
     *
     * @param login
     * @param id
     * @throws java.lang.Exception
     */
    public InfoService(String login, int id) throws Exception {
        APIService api = new APIService();
        initComponents();
        info(api.GetInfo(login, id));
        Events(login, id);
    }

    /**
     * Mostra os dados no formulário
     *
     * @param info
     * @throws MalformedURLException
     * @throws IOException
     */
    private void info(String[] info) throws MalformedURLException, IOException {
        l_service.setText(info[0]);
        l_name.setText(info[1]);
        l_price.setText(info[2]);
        l_description.setText("<html>" + info[3] + "</html>");
        ImageIcon icon = new ImageIcon(new URL(info[4]));
        Image image = icon.getImage();
        Image newimg = image.getScaledInstance(300, 180, java.awt.Image.SCALE_SMOOTH);
        icon = new ImageIcon(newimg);
        l_photo.setIcon(icon);
    }

    /**
     * Mostra os eventos
     *
     * @param login
     * @param idService
     */
    private void Events(final String login, final int idService) {
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    BT_EDIT(evt, login, idService);
                } catch (Exception ex) {
                    Logger.getLogger(InfoService.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     * Abre a form de editar serviço
     *
     * @param evt
     * @param login
     * @param idService
     * @throws Exception
     */
    private void BT_EDIT(java.awt.event.ActionEvent evt, String login, int idService) throws Exception {
        new EditService(login, idService).setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        l_service = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        l_photo = new javax.swing.JLabel();
        bt_edit = new javax.swing.JButton();
        l_name = new javax.swing.JLabel();
        l_price = new javax.swing.JLabel();
        l_description = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GestRepair - Informação do Serviço");
        setResizable(false);

        jLabel1.setText("Serviço n.º:");

        l_service.setText("serviço");

        jLabel3.setText("Nome:");

        jLabel2.setText("Preço:");

        jLabel4.setText("Descrição:");

        jLabel5.setText("Imagem:");

        bt_edit.setText("Editar Serviço");

        l_name.setText("name");

        l_price.setText("price");

        l_description.setText("desc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_name)
                            .addComponent(l_service)
                            .addComponent(l_price)))
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(l_description, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_edit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(l_service)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(l_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(l_price))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_description, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_edit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(639, 309));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel l_description;
    private javax.swing.JLabel l_name;
    private javax.swing.JLabel l_photo;
    private javax.swing.JLabel l_price;
    private javax.swing.JLabel l_service;
    // End of variables declaration//GEN-END:variables
}
