/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package services;

import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Convite
 */
public class MainServices extends javax.swing.JFrame {

    public String log;

    /**
     * Creates new form mainVehicles
     *
     * @param login
     */
    public MainServices(String login) {
        initComponents();
        Events(login);
    }

    /**
     * Mostra os eventos
     *
     * @param login
     */
    private void Events(final String login) {
        bt_create.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ADD_SV(evt, login);
            }
        });
        bt_listServices.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_SH_SV(evt, login);
            }
        });

    }

    /**
     * Mostra a tabela de serviços
     *
     * @param evt
     * @param login
     */
    private void BT_SH_SV(java.awt.event.ActionEvent evt, String login) {
        try {
            new Table_Services(login).setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(MainServices.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * Abre a Form para adicionar serviços
     * 
     * @param evt
     * @param login 
     */
    private void BT_ADD_SV(java.awt.event.ActionEvent evt, String login) {
        new Create_Service(login).setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_listServices = new javax.swing.JButton();
        bt_create = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GestRepair - Menu Serviços");
        setResizable(false);

        bt_listServices.setText("Lista de Serviços");

        bt_create.setText("Adicionar Serviço");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_listServices, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bt_create, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_listServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(654, 84));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_create;
    private javax.swing.JButton bt_listServices;
    // End of variables declaration//GEN-END:variables
}
